/**
 * MAZARE3_SHOWCASE_2026 — presentation dataset definitions (local/dev only).
 * Customer-facing names are fictional; identity is via slug/email markers only.
 */
import type { PropertyType } from '../generated/client/index.js';

export const SHOWCASE_MARKER = 'MAZARE3_SHOWCASE_2026';
export const SHOWCASE_SLUG_PREFIX = 'sc26-';
export const SHOWCASE_EMAIL_PREFIX = 'showcase.2026.';
export const SHOWCASE_EMAIL_DOMAIN = 'mazare3.local';
export const SHOWCASE_PASSWORD = 'ShowcaseLocal2026!';

/** Royalty-free Unsplash lifestyle/property imagery (same architecture as prisma/seed.ts). */
const U = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=80`;

/** Unique source URLs; each property takes a 10-image window (no duplicates within a property). */
export const SHOWCASE_IMAGE_POOL: string[] = [
  U('photo-1571896349842-33c89424de2d'),
  U('photo-1600607687939-ce8a6c25118c'),
  U('photo-1602343168117-bb8ffe3e2e9f'),
  U('photo-1613490493576-7fde63acd811'),
  U('photo-1518780664697-55e3ad937233'),
  U('photo-1500382017468-9049fed747ef'),
  U('photo-1566073771259-6a8506099945'),
  U('photo-1520250497591-112f2f40a3f4'),
  U('photo-1551882547-ff40c63fe5fa'),
  U('photo-1600596542815-ffad4c1539a9'),
  U('photo-1600585154340-be6161a56a0c'),
  U('photo-1600047509807-ba8f99d2cdde'),
  U('photo-1600566753190-17f0baa2a6c3'),
  U('photo-1600210492486-724fe5c67fb0'),
  U('photo-1600607687644-c7171b42498f'),
  U('photo-1600573472592-401b489a3cdc'),
  U('photo-1499793983690-e29da59ef1c2'),
  U('photo-1506905925346-21bda4d32df4'),
  U('photo-1476514525535-07fb3b4ae5f1'),
  U('photo-1564013799919-ab600027ffc6'),
  U('photo-1512917774080-9991f1c4c750'),
  U('photo-1578683010236-d716f9a3f461'),
  U('photo-1590490360182-c33d57733427'),
  U('photo-1582719478250-c89cae4dc85b'),
  U('photo-1564501049412-61c2a3083791'),
  U('photo-1571003123894-1f0594d2b5d9'),
  U('photo-1584132967334-10e028bd69f7'),
  U('photo-1596394516093-501ba68a0ba6'),
  U('photo-1522708323590-d24dbb6b0267'),
  U('photo-1502672260266-1c1ef2d93688'),
  U('photo-1560448204-e02f11c3d0e2'),
  U('photo-1484154218962-a197022b5858'),
  U('photo-1493809842364-78817add7ffb'),
  U('photo-1522771739844-6a9f6d5f14af'),
  U('photo-1536376072261-38c75010e6c9'),
  U('photo-1600585154526-990dced4db0d'),
  U('photo-1600566752355-35792bedcfea'),
  U('photo-1600047509782-20d39509f26d'),
  U('photo-1600210491892-03d54c0aaf87'),
  U('photo-1600607687920-4e2a09cf159d'),
  U('photo-1600585154363-67eb9e2e2099'),
  U('photo-1540518614846-7eded433c457'),
  U('photo-1554995207-c18c203602cb'),
  U('photo-1586023492125-27b2c045efd7'),
  U('photo-1618221195710-dd6b41faaea6'),
  U('photo-1616486338812-3dadae4b4ace'),
  U('photo-1570129477492-45c003edd2be'),
  U('photo-1568605114967-8130f3a36994'),
  U('photo-1605276374104-dee2a0ed3cd6'),
  U('photo-1505693416388-ac5ce068fe85'),
  U('photo-1501183638710-841dd1904471'),
  U('photo-1480074568708-e7b720bb3f09'),
  U('photo-1513584684374-8bab748fbf90'),
  U('photo-1470071459604-3b5ec3a7fe05'),
  U('photo-1501785888041-af3ef285b470'),
  U('photo-1441974231531-c6227db76b6e'),
  U('photo-1616594039964-ae9021a400a0'),
  U('photo-1618220179428-22790b461013'),
  U('photo-1588854337236-6889d631faa8'),
  U('photo-1595526114035-0d45ed16cfbf'),
  U('photo-1426604966848-d7adac402bff'),
  U('photo-1500530855697-b586d89ba3ee'),
];

function imgs(start: number): { url: string; altAr: string; altEn: string }[] {
  const labels = [
    ['واجهة العقار', 'Property exterior'],
    ['المسبح', 'Pool'],
    ['جلسات خارجية', 'Outdoor seating'],
    ['جلسات داخلية', 'Indoor seating'],
    ['الحديقة', 'Garden'],
    ['زاوية خارجية ثانية', 'Second exterior'],
    ['إطلالة مسائية', 'Evening view'],
    ['تفاصيل المرافق', 'Amenity detail'],
    ['منطقة الشواء', 'BBQ / dining'],
    ['أجواء المكان', 'Lifestyle angle'],
  ] as const;
  const n = SHOWCASE_IMAGE_POOL.length;
  return labels.map(([altAr, altEn], i) => ({
    url: SHOWCASE_IMAGE_POOL[(start + i) % n]!,
    altAr,
    altEn,
  }));
}

export type ShowcasePropertyDef = {
  num: number;
  slug: string;
  type: PropertyType;
  titleAr: string;
  titleEn: string;
  descriptionAr: string;
  descriptionEn: string;
  city: string;
  area: string;
  approximateAddress: string;
  exactAddress: string;
  lat: number;
  lng: number;
  capacity: number;
  bedrooms: number;
  bathrooms: number;
  poolsCount: number;
  hasIndoorPool: boolean;
  hasHeatedPool: boolean;
  hasFootballField: boolean;
  allowsFamilies: boolean;
  allowsYouth: boolean;
  allowsOvernight: boolean;
  allowsEvents: boolean;
  instantBookingEnabled: boolean;
  basePrice: number;
  checkInTime: string;
  checkOutTime: string;
  amenityKeys: string[];
  rules: { titleAr: string; titleEn: string }[];
  ownerIndex: number;
  featured: boolean;
  offer: boolean;
  sponsored: boolean;
  offerDiscountPercent?: number;
};

export const SHOWCASE_OWNERS = [
  {
    email: `${SHOWCASE_EMAIL_PREFIX}owner1@${SHOWCASE_EMAIL_DOMAIN}`,
    name: 'رامي الحوراني',
    displayName: 'رامي الحوراني',
    phone: '+962790010001',
    city: 'amman',
    area: 'ناعور',
  },
  {
    email: `${SHOWCASE_EMAIL_PREFIX}owner2@${SHOWCASE_EMAIL_DOMAIN}`,
    name: 'ليلى السعدي',
    displayName: 'ليلى السعدي',
    phone: '+962790010002',
    city: 'salt',
    area: 'السلط',
  },
  {
    email: `${SHOWCASE_EMAIL_PREFIX}owner3@${SHOWCASE_EMAIL_DOMAIN}`,
    name: 'فادي الجبالي',
    displayName: 'فادي الجبالي',
    phone: '+962790010003',
    city: 'jerash',
    area: 'جرش',
  },
  {
    email: `${SHOWCASE_EMAIL_PREFIX}owner4@${SHOWCASE_EMAIL_DOMAIN}`,
    name: 'نور الرفاعي',
    displayName: 'نور الرفاعي',
    phone: '+962790010004',
    city: 'madaba',
    area: 'مادبا',
  },
] as const;

export const SHOWCASE_PROPERTIES: ShowcasePropertyDef[] = [
  {
    num: 1,
    slug: `${SHOWCASE_SLUG_PREFIX}wadi-sarw`,
    type: 'farm',
    titleAr: 'مزرعة وادي السرو',
    titleEn: 'Wadi Al-Sarw Farm',
    descriptionAr:
      'مزرعة هادئة في منطقة مرتفعة بإطلالة مفتوحة، مناسبة للجلسات العائلية. تحتوي على مسبح خارجي وجلسات داخلية وخارجية ومساحة للشواء.',
    descriptionEn:
      'A quiet hillside farm with open views for family gatherings. Outdoor pool, indoor and outdoor seating, and a BBQ area.',
    city: 'amman',
    area: 'ناعور',
    approximateAddress: 'ناعور — ضواحي عمان الغربية',
    exactAddress: `${SHOWCASE_MARKER} | ناعور — طريق فرعي (يُكشف بعد الحجز)`,
    lat: 31.8685,
    lng: 35.8212,
    capacity: 20,
    bedrooms: 3,
    bathrooms: 2,
    poolsCount: 1,
    hasIndoorPool: false,
    hasHeatedPool: false,
    hasFootballField: false,
    allowsFamilies: true,
    allowsYouth: false,
    allowsOvernight: true,
    allowsEvents: false,
    instantBookingEnabled: true,
    basePrice: 145,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    amenityKeys: ['pool', 'bbq', 'wifi', 'parking', 'garden', 'ac'],
    rules: [
      { titleAr: 'الالتزام بعدد الضيوف', titleEn: 'Respect guest capacity' },
      { titleAr: 'ممنوع التدخين داخل الغرف', titleEn: 'No smoking indoors' },
    ],
    ownerIndex: 0,
    featured: true,
    offer: true,
    sponsored: false,
    offerDiscountPercent: 12,
  },
  {
    num: 2,
    slug: `${SHOWCASE_SLUG_PREFIX}blue-palm`,
    type: 'chalet',
    titleAr: 'شاليه بلو بالم',
    titleEn: 'Blue Palm Chalet',
    descriptionAr:
      'شاليه أنيق بتصميم حديث ومسبح خاص، مناسب للعائلات الصغيرة. جلسات مريحة وإضاءة مسائية هادئة.',
    descriptionEn:
      'A modern chalet with a private pool for small families. Comfortable seating and soft evening lighting.',
    city: 'dead_sea',
    area: 'سويمة',
    approximateAddress: 'البحر الميت — سويمة',
    exactAddress: `${SHOWCASE_MARKER} | سويمة (يُكشف بعد الحجز)`,
    lat: 31.7168,
    lng: 35.5824,
    capacity: 12,
    bedrooms: 2,
    bathrooms: 2,
    poolsCount: 1,
    hasIndoorPool: false,
    hasHeatedPool: true,
    hasFootballField: false,
    allowsFamilies: true,
    allowsYouth: false,
    allowsOvernight: true,
    allowsEvents: false,
    instantBookingEnabled: true,
    basePrice: 210,
    checkInTime: '15:00',
    checkOutTime: '12:00',
    amenityKeys: ['pool', 'heated_pool', 'bbq', 'wifi', 'parking', 'ac'],
    rules: [{ titleAr: 'ممنوع الحيوانات الأليفة', titleEn: 'No pets' }],
    ownerIndex: 0,
    featured: true,
    offer: false,
    sponsored: true,
  },
  {
    num: 3,
    slug: `${SHOWCASE_SLUG_PREFIX}telal-salt`,
    type: 'farm',
    titleAr: 'مزرعة تلال السلط',
    titleEn: 'Salt Hills Farm',
    descriptionAr:
      'مزرعة واسعة على تلال السلط مع حديقة زيتون وملعب كرة صغير. مناسبة للعائلات والشباب.',
    descriptionEn:
      'A spacious farm on Salt hills with an olive garden and a small football pitch for families and youth.',
    city: 'salt',
    area: 'السلط',
    approximateAddress: 'السلط — المناطق المرتفعة',
    exactAddress: `${SHOWCASE_MARKER} | السلط (يُكشف بعد الحجز)`,
    lat: 32.0392,
    lng: 35.7272,
    capacity: 28,
    bedrooms: 4,
    bathrooms: 3,
    poolsCount: 1,
    hasIndoorPool: false,
    hasHeatedPool: false,
    hasFootballField: true,
    allowsFamilies: true,
    allowsYouth: true,
    allowsOvernight: true,
    allowsEvents: true,
    instantBookingEnabled: false,
    basePrice: 175,
    checkInTime: '13:00',
    checkOutTime: '11:00',
    amenityKeys: ['pool', 'football', 'bbq', 'parking', 'garden', 'events', 'wifi'],
    rules: [{ titleAr: 'ممنوع الضوضاء بعد منتصف الليل', titleEn: 'Quiet hours after midnight' }],
    ownerIndex: 1,
    featured: true,
    offer: true,
    sponsored: false,
    offerDiscountPercent: 10,
  },
  {
    num: 4,
    slug: `${SHOWCASE_SLUG_PREFIX}sindyan`,
    type: 'chalet',
    titleAr: 'شاليهات السنديان',
    titleEn: 'Al-Sindyan Chalets',
    descriptionAr:
      'مجموعة شاليهات وسط أشجار السنديان قرب عجلون. أجواء باردة صيفاً ومناسبة للجلسات الهادئة.',
    descriptionEn:
      'Chalets among oak trees near Ajloun. Cooler summer evenings and quiet seating areas.',
    city: 'ajloun',
    area: 'عجلون',
    approximateAddress: 'عجلون — المناطق الحرجية',
    exactAddress: `${SHOWCASE_MARKER} | عجلون (يُكشف بعد الحجز)`,
    lat: 32.3325,
    lng: 35.7517,
    capacity: 16,
    bedrooms: 3,
    bathrooms: 2,
    poolsCount: 1,
    hasIndoorPool: false,
    hasHeatedPool: false,
    hasFootballField: false,
    allowsFamilies: true,
    allowsYouth: false,
    allowsOvernight: true,
    allowsEvents: false,
    instantBookingEnabled: true,
    basePrice: 160,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    amenityKeys: ['pool', 'bbq', 'wifi', 'parking', 'garden', 'ac'],
    rules: [{ titleAr: 'الالتزام بمواعيد الدخول والخروج', titleEn: 'Respect check-in/out times' }],
    ownerIndex: 2,
    featured: true,
    offer: false,
    sponsored: false,
  },
  {
    num: 5,
    slug: `${SHOWCASE_SLUG_PREFIX}nasmat-jabal`,
    type: 'istiraha',
    titleAr: 'مزرعة نسمة الجبل',
    titleEn: 'Mountain Breeze Farm',
    descriptionAr:
      'استراحة جبلية بإطلالة واسعة ومساحات خارجية مظللة. مثالية للنهار العائلي بدون مبيت إن رغبت.',
    descriptionEn:
      'A mountain istiraha with wide views and shaded outdoor space. Ideal for daytime family visits.',
    city: 'jerash',
    area: 'سوف',
    approximateAddress: 'جرش — سوف',
    exactAddress: `${SHOWCASE_MARKER} | سوف (يُكشف بعد الحجز)`,
    lat: 32.3101,
    lng: 35.8914,
    capacity: 22,
    bedrooms: 2,
    bathrooms: 2,
    poolsCount: 1,
    hasIndoorPool: false,
    hasHeatedPool: false,
    hasFootballField: false,
    allowsFamilies: true,
    allowsYouth: true,
    allowsOvernight: false,
    allowsEvents: false,
    instantBookingEnabled: true,
    basePrice: 95,
    checkInTime: '10:00',
    checkOutTime: '22:00',
    amenityKeys: ['pool', 'bbq', 'parking', 'garden', 'kids_pool'],
    rules: [{ titleAr: 'المبيت غير متاح', titleEn: 'Overnight stays not available' }],
    ownerIndex: 2,
    featured: false,
    offer: true,
    sponsored: false,
    offerDiscountPercent: 15,
  },
  {
    num: 6,
    slug: `${SHOWCASE_SLUG_PREFIX}lavender`,
    type: 'chalet',
    titleAr: 'شاليه لافندر',
    titleEn: 'Lavender Chalet',
    descriptionAr:
      'شاليه صغير بطابع هادئ وحديقة بسيطة. مناسب للأزواج والعائلات الصغيرة الباحثة عن خصوصية.',
    descriptionEn:
      'A compact quiet chalet with a simple garden. Suited to couples and small families seeking privacy.',
    city: 'madaba',
    area: 'مادبا',
    approximateAddress: 'مادبا — أطراف المدينة',
    exactAddress: `${SHOWCASE_MARKER} | مادبا (يُكشف بعد الحجز)`,
    lat: 31.7167,
    lng: 35.7939,
    capacity: 8,
    bedrooms: 1,
    bathrooms: 1,
    poolsCount: 1,
    hasIndoorPool: false,
    hasHeatedPool: false,
    hasFootballField: false,
    allowsFamilies: true,
    allowsYouth: false,
    allowsOvernight: true,
    allowsEvents: false,
    instantBookingEnabled: true,
    basePrice: 85,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    amenityKeys: ['pool', 'wifi', 'parking', 'ac', 'bbq'],
    rules: [{ titleAr: 'الحد الأقصى للضيوف ٨', titleEn: 'Max 8 guests' }],
    ownerIndex: 3,
    featured: false,
    offer: false,
    sponsored: false,
  },
  {
    num: 7,
    slug: `${SHOWCASE_SLUG_PREFIX}wadi-zaytoun`,
    type: 'farm',
    titleAr: 'مزرعة وادي الزيتون',
    titleEn: 'Olive Valley Farm',
    descriptionAr:
      'مزرعة محاطة بأشجار الزيتون قرب جرش مع مسبح وجلسات واسعة للمناسبات العائلية الصغيرة.',
    descriptionEn:
      'An olive-grove farm near Jerash with a pool and generous seating for small family gatherings.',
    city: 'jerash',
    area: 'جرش',
    approximateAddress: 'محيط جرش',
    exactAddress: `${SHOWCASE_MARKER} | جرش (يُكشف بعد الحجز)`,
    lat: 32.2721,
    lng: 35.8992,
    capacity: 30,
    bedrooms: 4,
    bathrooms: 3,
    poolsCount: 1,
    hasIndoorPool: false,
    hasHeatedPool: false,
    hasFootballField: false,
    allowsFamilies: true,
    allowsYouth: true,
    allowsOvernight: true,
    allowsEvents: true,
    instantBookingEnabled: false,
    basePrice: 185,
    checkInTime: '13:00',
    checkOutTime: '11:00',
    amenityKeys: ['pool', 'bbq', 'garden', 'parking', 'wifi', 'events', 'ac'],
    rules: [{ titleAr: 'المناسبات الكبيرة تحتاج تنسيق مسبق', titleEn: 'Large events need prior arrangement' }],
    ownerIndex: 2,
    featured: true,
    offer: true,
    sponsored: false,
    offerDiscountPercent: 8,
  },
  {
    num: 8,
    slug: `${SHOWCASE_SLUG_PREFIX}sky-view`,
    type: 'villa',
    titleAr: 'شاليه سكاي فيو',
    titleEn: 'Sky View Villa',
    descriptionAr:
      'فيلا بإطلالة مرتفعة قرب عمان مع مسبح مدفأ وجلسات داخلية واسعة. مناسبة للعائلات المتوسطة.',
    descriptionEn:
      'An elevated villa near Amman with a heated pool and spacious indoor seating for mid-size families.',
    city: 'amman',
    area: 'محيص',
    approximateAddress: 'محيص — غرب عمان',
    exactAddress: `${SHOWCASE_MARKER} | محيص (يُكشف بعد الحجز)`,
    lat: 31.9824,
    lng: 35.7681,
    capacity: 18,
    bedrooms: 4,
    bathrooms: 3,
    poolsCount: 1,
    hasIndoorPool: false,
    hasHeatedPool: true,
    hasFootballField: false,
    allowsFamilies: true,
    allowsYouth: false,
    allowsOvernight: true,
    allowsEvents: false,
    instantBookingEnabled: true,
    basePrice: 220,
    checkInTime: '15:00',
    checkOutTime: '12:00',
    amenityKeys: ['pool', 'heated_pool', 'bbq', 'wifi', 'parking', 'ac', 'garden'],
    rules: [{ titleAr: 'ممنوع التدخين داخل الفيلا', titleEn: 'No indoor smoking' }],
    ownerIndex: 0,
    featured: true,
    offer: false,
    sponsored: true,
  },
  {
    num: 9,
    slug: `${SHOWCASE_SLUG_PREFIX}reef-jerash`,
    type: 'farm',
    titleAr: 'مزرعة ريف جرش',
    titleEn: 'Jerash Countryside Farm',
    descriptionAr:
      'مزرعة ريفية بسيطة مع مسبح أطفال وجلسات خارجية. خيار عملي للزيارات النهارية والعائلية.',
    descriptionEn:
      'A simple countryside farm with a kids pool and outdoor seating for daytime family visits.',
    city: 'jerash',
    area: 'قفقفا',
    approximateAddress: 'جرش — قفقفا',
    exactAddress: `${SHOWCASE_MARKER} | قفقفا (يُكشف بعد الحجز)`,
    lat: 32.2456,
    lng: 35.8623,
    capacity: 24,
    bedrooms: 3,
    bathrooms: 2,
    poolsCount: 1,
    hasIndoorPool: false,
    hasHeatedPool: false,
    hasFootballField: false,
    allowsFamilies: true,
    allowsYouth: true,
    allowsOvernight: true,
    allowsEvents: false,
    instantBookingEnabled: true,
    basePrice: 120,
    checkInTime: '12:00',
    checkOutTime: '11:00',
    amenityKeys: ['pool', 'kids_pool', 'bbq', 'parking', 'garden', 'wifi'],
    rules: [{ titleAr: 'الإشراف على الأطفال عند المسبح', titleEn: 'Supervise children near the pool' }],
    ownerIndex: 2,
    featured: false,
    offer: false,
    sponsored: false,
  },
  {
    num: 10,
    slug: `${SHOWCASE_SLUG_PREFIX}palm-hill`,
    type: 'chalet',
    titleAr: 'شاليه بالم هيل',
    titleEn: 'Palm Hill Chalet',
    descriptionAr:
      'شاليه على طريق المطار الجنوبي مع مسبح وخصوصية جيدة. مناسب للعائلات الباحثة عن موقع قريب من عمان.',
    descriptionEn:
      'A chalet on the southern Airport Road corridor with a pool and solid privacy near Amman.',
    city: 'amman',
    area: 'طريق المطار',
    approximateAddress: 'عمان — طريق المطار الجنوبي',
    exactAddress: `${SHOWCASE_MARKER} | طريق المطار (يُكشف بعد الحجز)`,
    lat: 31.8221,
    lng: 35.9487,
    capacity: 14,
    bedrooms: 2,
    bathrooms: 2,
    poolsCount: 1,
    hasIndoorPool: false,
    hasHeatedPool: false,
    hasFootballField: false,
    allowsFamilies: true,
    allowsYouth: false,
    allowsOvernight: true,
    allowsEvents: false,
    instantBookingEnabled: false,
    basePrice: 135,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    amenityKeys: ['pool', 'bbq', 'wifi', 'parking', 'ac'],
    rules: [{ titleAr: 'الحجز يتطلب موافقة المالك', titleEn: 'Owner approval required' }],
    ownerIndex: 0,
    featured: true,
    offer: true,
    sponsored: false,
    offerDiscountPercent: 10,
  },
  {
    num: 11,
    slug: `${SHOWCASE_SLUG_PREFIX}ghuroob-madaba`,
    type: 'farm',
    titleAr: 'مزرعة غروب مادبا',
    titleEn: 'Madaba Sunset Farm',
    descriptionAr:
      'مزرعة بإطلالة غروب مفتوحة قرب مادبا ومساحات للشواء والجلسات الخارجية. أجواء هادئة للعائلات.',
    descriptionEn:
      'A Madaba-area farm with open sunset views, BBQ space, and outdoor seating for quiet family days.',
    city: 'madaba',
    area: 'ماعين',
    approximateAddress: 'مادبا — ماعين',
    exactAddress: `${SHOWCASE_MARKER} | ماعين (يُكشف بعد الحجز)`,
    lat: 31.6794,
    lng: 35.7331,
    capacity: 26,
    bedrooms: 3,
    bathrooms: 2,
    poolsCount: 1,
    hasIndoorPool: false,
    hasHeatedPool: false,
    hasFootballField: true,
    allowsFamilies: true,
    allowsYouth: true,
    allowsOvernight: true,
    allowsEvents: false,
    instantBookingEnabled: true,
    basePrice: 155,
    checkInTime: '13:00',
    checkOutTime: '11:00',
    amenityKeys: ['pool', 'football', 'bbq', 'parking', 'garden', 'wifi'],
    rules: [{ titleAr: 'الالتزام بمواقف السيارات المخصصة', titleEn: 'Use designated parking' }],
    ownerIndex: 3,
    featured: false,
    offer: true,
    sponsored: false,
    offerDiscountPercent: 12,
  },
  {
    num: 12,
    slug: `${SHOWCASE_SLUG_PREFIX}al-wadi`,
    type: 'chalet',
    titleAr: 'شاليه الوادي',
    titleEn: 'Al-Wadi Chalet',
    descriptionAr:
      'شاليه في فحيص/محيط غرب عمان بمسبح وجلسات داخلية مريحة. خيار متوازن بين القرب من المدينة والهدوء.',
    descriptionEn:
      'A Fuheis-area chalet with a pool and comfortable indoor seating — close to Amman with a quieter feel.',
    city: 'amman',
    area: 'فحيص',
    approximateAddress: 'فحيص — غرب عمان',
    exactAddress: `${SHOWCASE_MARKER} | فحيص (يُكشف بعد الحجز)`,
    lat: 32.0012,
    lng: 35.7804,
    capacity: 10,
    bedrooms: 2,
    bathrooms: 1,
    poolsCount: 1,
    hasIndoorPool: false,
    hasHeatedPool: false,
    hasFootballField: false,
    allowsFamilies: true,
    allowsYouth: false,
    allowsOvernight: true,
    allowsEvents: false,
    instantBookingEnabled: true,
    basePrice: 110,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    amenityKeys: ['pool', 'bbq', 'wifi', 'parking', 'ac', 'garden'],
    rules: [{ titleAr: 'المحافظة على نظافة الموقع', titleEn: 'Keep the property tidy' }],
    ownerIndex: 1,
    featured: true,
    offer: false,
    sponsored: false,
  },
];

export function imagesForProperty(num: number) {
  return imgs((num - 1) * 10);
}

export function showcaseOwnerEmail(index: number) {
  return SHOWCASE_OWNERS[index]!.email;
}
