// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/[locale]" | "/[locale]/about" | "/[locale]/account" | "/[locale]/account/bookings" | "/[locale]/account/favorites" | "/[locale]/account/notifications" | "/[locale]/account/support" | "/[locale]/admin" | "/[locale]/admin/audit-logs" | "/[locale]/admin/availability" | "/[locale]/admin/bookings" | "/[locale]/admin/coupons" | "/[locale]/admin/disputes" | "/[locale]/admin/owners" | "/[locale]/admin/owners/[id]" | "/[locale]/admin/payments" | "/[locale]/admin/payouts" | "/[locale]/admin/properties" | "/[locale]/admin/properties/[id]" | "/[locale]/admin/refunds" | "/[locale]/admin/reviews" | "/[locale]/admin/sponsorship" | "/[locale]/admin/support" | "/[locale]/admin/users" | "/[locale]/auth" | "/[locale]/become-owner" | "/[locale]/booking-payment" | "/[locale]/cancellation-refund" | "/[locale]/checkout/[bookingId]" | "/[locale]/checkout/[bookingId]/return" | "/[locale]/contact" | "/[locale]/forgot-password" | "/[locale]/login" | "/[locale]/owner" | "/[locale]/owner/availability" | "/[locale]/owner/bookings" | "/[locale]/owner/payouts" | "/[locale]/owner/properties" | "/[locale]/owner/properties/[id]" | "/[locale]/owner/properties/[id]/edit" | "/[locale]/owner/properties/new" | "/[locale]/owner/reviews" | "/[locale]/privacy" | "/[locale]/properties/[slug]" | "/[locale]/reset-password" | "/[locale]/search" | "/[locale]/signup" | "/[locale]/terms"
type AppRouteHandlerRoutes = "/api/payment-return/[paymentId]" | "/api/payment-return/[paymentId]/ack" | "/api/paytabs/browser-return"
type PageRoutes = never
type LayoutRoutes = "/" | "/[locale]" | "/[locale]/admin" | "/[locale]/owner"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/[locale]": { "locale": string; }
  "/[locale]/about": { "locale": string; }
  "/[locale]/account": { "locale": string; }
  "/[locale]/account/bookings": { "locale": string; }
  "/[locale]/account/favorites": { "locale": string; }
  "/[locale]/account/notifications": { "locale": string; }
  "/[locale]/account/support": { "locale": string; }
  "/[locale]/admin": { "locale": string; }
  "/[locale]/admin/audit-logs": { "locale": string; }
  "/[locale]/admin/availability": { "locale": string; }
  "/[locale]/admin/bookings": { "locale": string; }
  "/[locale]/admin/coupons": { "locale": string; }
  "/[locale]/admin/disputes": { "locale": string; }
  "/[locale]/admin/owners": { "locale": string; }
  "/[locale]/admin/owners/[id]": { "locale": string; "id": string; }
  "/[locale]/admin/payments": { "locale": string; }
  "/[locale]/admin/payouts": { "locale": string; }
  "/[locale]/admin/properties": { "locale": string; }
  "/[locale]/admin/properties/[id]": { "locale": string; "id": string; }
  "/[locale]/admin/refunds": { "locale": string; }
  "/[locale]/admin/reviews": { "locale": string; }
  "/[locale]/admin/sponsorship": { "locale": string; }
  "/[locale]/admin/support": { "locale": string; }
  "/[locale]/admin/users": { "locale": string; }
  "/[locale]/auth": { "locale": string; }
  "/[locale]/become-owner": { "locale": string; }
  "/[locale]/booking-payment": { "locale": string; }
  "/[locale]/cancellation-refund": { "locale": string; }
  "/[locale]/checkout/[bookingId]": { "locale": string; "bookingId": string; }
  "/[locale]/checkout/[bookingId]/return": { "locale": string; "bookingId": string; }
  "/[locale]/contact": { "locale": string; }
  "/[locale]/forgot-password": { "locale": string; }
  "/[locale]/login": { "locale": string; }
  "/[locale]/owner": { "locale": string; }
  "/[locale]/owner/availability": { "locale": string; }
  "/[locale]/owner/bookings": { "locale": string; }
  "/[locale]/owner/payouts": { "locale": string; }
  "/[locale]/owner/properties": { "locale": string; }
  "/[locale]/owner/properties/[id]": { "locale": string; "id": string; }
  "/[locale]/owner/properties/[id]/edit": { "locale": string; "id": string; }
  "/[locale]/owner/properties/new": { "locale": string; }
  "/[locale]/owner/reviews": { "locale": string; }
  "/[locale]/privacy": { "locale": string; }
  "/[locale]/properties/[slug]": { "locale": string; "slug": string; }
  "/[locale]/reset-password": { "locale": string; }
  "/[locale]/search": { "locale": string; }
  "/[locale]/signup": { "locale": string; }
  "/[locale]/terms": { "locale": string; }
  "/api/payment-return/[paymentId]": { "paymentId": string; }
  "/api/payment-return/[paymentId]/ack": { "paymentId": string; }
  "/api/paytabs/browser-return": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/[locale]": never
  "/[locale]/admin": never
  "/[locale]/owner": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
