// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/[locale]/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/about">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/account/bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account/bookings">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/account/bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/account/favorites/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account/favorites">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/account/favorites/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/account/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/account/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/account/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/account/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/account/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/account/support">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/account/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/audit-logs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/audit-logs">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/audit-logs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/availability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/availability">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/availability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/bookings">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/coupons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/coupons">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/coupons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/disputes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/disputes">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/disputes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/owners/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/owners/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/owners/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/owners/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/owners">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/owners/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/payments">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/payouts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/payouts">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/payouts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/properties/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/properties/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/properties/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/properties/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/properties">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/properties/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/refunds/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/refunds">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/refunds/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/reviews">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/sponsorship/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/sponsorship">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/sponsorship/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/support">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/auth">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/become-owner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/become-owner">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/become-owner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/booking-payment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/booking-payment">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/booking-payment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/cancellation-refund/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/cancellation-refund">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/cancellation-refund/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/checkout/[bookingId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/checkout/[bookingId]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/checkout/[bookingId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/checkout/[bookingId]/return/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/checkout/[bookingId]/return">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/checkout/[bookingId]/return/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/contact">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/login">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/owner/availability/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/owner/availability">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/owner/availability/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/owner/bookings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/owner/bookings">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/owner/bookings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/owner/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/owner">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/owner/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/owner/payouts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/owner/payouts">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/owner/payouts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/owner/properties/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/owner/properties/[id]/edit">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/owner/properties/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/owner/properties/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/owner/properties/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/owner/properties/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/owner/properties/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/owner/properties/new">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/owner/properties/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/owner/properties/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/owner/properties">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/owner/properties/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/owner/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/owner/reviews">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/owner/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/properties/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/properties/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/properties/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/search/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/search">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/search/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/signup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/signup">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/signup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[locale]/terms">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payment-return/[paymentId]/ack/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment-return/[paymentId]/ack">> = Specific
  const handler = {} as typeof import("../../src/app/api/payment-return/[paymentId]/ack/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/payment-return/[paymentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment-return/[paymentId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/payment-return/[paymentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/paytabs/browser-return/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/paytabs/browser-return">> = Specific
  const handler = {} as typeof import("../../src/app/api/paytabs/browser-return/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/[locale]/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/admin">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/[locale]/owner/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[locale]/owner">> = Specific
  const handler = {} as typeof import("../../src/app/[locale]/owner/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
