/** Operator identity tokens — never invent unresolved privacy/DPO/PSP values. */
export const LEGAL_CONTENT_PLACEHOLDERS = {
  LEGAL_ENTITY_NAME: '[[LEGAL_ENTITY_NAME]]',
  LEGAL_ENTITY_NAME_AR: '[[LEGAL_ENTITY_NAME_AR]]',
  LEGAL_ENTITY_NAME_EN: '[[LEGAL_ENTITY_NAME_EN]]',
  LEGAL_FORM_AR: '[[LEGAL_FORM_AR]]',
  LEGAL_FORM_EN: '[[LEGAL_FORM_EN]]',
  LEGAL_ENTITY_INTRO_AR: '[[LEGAL_ENTITY_INTRO_AR]]',
  LEGAL_ENTITY_INTRO_EN: '[[LEGAL_ENTITY_INTRO_EN]]',
  REGISTERED_ADDRESS: '[[REGISTERED_ADDRESS]]',
  REGISTERED_ADDRESS_AR: '[[REGISTERED_ADDRESS_AR]]',
  REGISTERED_ADDRESS_EN: '[[REGISTERED_ADDRESS_EN]]',
  LEGAL_CONTACT_EMAIL: '[[LEGAL_CONTACT_EMAIL]]',
  PRIVACY_CONTACT_EMAIL: '[[PRIVACY_CONTACT_EMAIL]]',
  COMMERCIAL_REGISTRATION_NUMBER: '[[COMMERCIAL_REGISTRATION_NUMBER]]',
  NATIONAL_ESTABLISHMENT_NUMBER: '[[NATIONAL_ESTABLISHMENT_NUMBER]]',
  PROJECT_OPERATIONAL_EMAIL: '[[PROJECT_OPERATIONAL_EMAIL]]',
  PARTNERSHIP_CONTACT_PHONE: '[[PARTNERSHIP_CONTACT_PHONE]]',
  DPO_OR_PRIVACY_CONTACT: '[[DPO_OR_PRIVACY_CONTACT]]',
  PAYMENT_PROVIDER_LEGAL_NAME: '[[PAYMENT_PROVIDER_LEGAL_NAME]]',
  PAYMENT_PROVIDER_PRIVACY_CONTACT: '[[PAYMENT_PROVIDER_PRIVACY_CONTACT]]',
  PAYMENT_PROVIDER_PROCESSING_REGION: '[[PAYMENT_PROVIDER_PROCESSING_REGION]]',
  /** Phase 3C.4B.2A / 2B / 2C — processor / hosting / retention unresolved until counsel + provider confirmation */
  DATABASE_PROVIDER_LEGAL_NAME: '[[DATABASE_PROVIDER_LEGAL_NAME]]',
  DATABASE_PROVIDER_PRIVACY_CONTACT: '[[DATABASE_PROVIDER_PRIVACY_CONTACT]]',
  PROCESSOR_REGION_NEON: '[[PROCESSOR_REGION_NEON]]',
  OBJECT_STORAGE_PROVIDER_LEGAL_NAME: '[[OBJECT_STORAGE_PROVIDER_LEGAL_NAME]]',
  OBJECT_STORAGE_PROVIDER_PRIVACY_CONTACT: '[[OBJECT_STORAGE_PROVIDER_PRIVACY_CONTACT]]',
  PROCESSOR_REGION_R2: '[[PROCESSOR_REGION_R2]]',
  ACTIVE_EMAIL_PROVIDER_LEGAL_NAME: '[[ACTIVE_EMAIL_PROVIDER_LEGAL_NAME]]',
  ACTIVE_EMAIL_PROVIDER_PRIVACY_CONTACT: '[[ACTIVE_EMAIL_PROVIDER_PRIVACY_CONTACT]]',
  ACTIVE_EMAIL_PROVIDER_PROCESSING_REGION: '[[ACTIVE_EMAIL_PROVIDER_PROCESSING_REGION]]',
  APP_HOSTING_PROVIDER: '[[APP_HOSTING_PROVIDER]]',
  APP_HOSTING_PROVIDER_PRIVACY_CONTACT: '[[APP_HOSTING_PROVIDER_PRIVACY_CONTACT]]',
  APP_HOSTING_REGION: '[[APP_HOSTING_REGION]]',
  GOOGLE_SIGNIN_PROVIDER_LEGAL_NAME: '[[GOOGLE_SIGNIN_PROVIDER_LEGAL_NAME]]',
  GOOGLE_SIGNIN_PROVIDER_PRIVACY_CONTACT: '[[GOOGLE_SIGNIN_PROVIDER_PRIVACY_CONTACT]]',
  GOOGLE_SIGNIN_PROCESSING_REGION: '[[GOOGLE_SIGNIN_PROCESSING_REGION]]',
  RETENTION_ACCOUNTS: '[[RETENTION_ACCOUNTS]]',
  RETENTION_BOOKINGS: '[[RETENTION_BOOKINGS]]',
  RETENTION_PAYMENTS: '[[RETENTION_PAYMENTS]]',
  RETENTION_KYC: '[[RETENTION_KYC]]',
  RETENTION_SETTLEMENTS: '[[RETENTION_SETTLEMENTS]]',
  RETENTION_LEGAL_ACCEPTANCES: '[[RETENTION_LEGAL_ACCEPTANCES]]',
  RETENTION_CONSENT_HISTORY: '[[RETENTION_CONSENT_HISTORY]]',
  RETENTION_AUDIT_LOGS: '[[RETENTION_AUDIT_LOGS]]',
  RETENTION_SUPPORT: '[[RETENTION_SUPPORT]]',
  RETENTION_PRIVACY_REQUESTS: '[[RETENTION_PRIVACY_REQUESTS]]',
  RETENTION_BREACH_RECORDS: '[[RETENTION_BREACH_RECORDS]]',
  /** @deprecated Prefer RETENTION_BREACH_RECORDS — retained for 3C.4B.2A historical corpus only */
  RETENTION_BREACH: '[[RETENTION_BREACH]]',
  RETENTION_EXACT_LOCATION: '[[RETENTION_EXACT_LOCATION]]',
  RETENTION_REVIEWS: '[[RETENTION_REVIEWS]]',
  RETENTION_LISTING_MEDIA: '[[RETENTION_LISTING_MEDIA]]',
  PRIVACY_POLICY_EFFECTIVE_DATE: '[[PRIVACY_POLICY_EFFECTIVE_DATE]]',
  PRIVACY_POLICY_LAST_UPDATED_DATE: '[[PRIVACY_POLICY_LAST_UPDATED_DATE]]',
  /**
   * Phase 3C.4C.2 — Owner settlement cadence not founder-locked for contractual wording.
   * Code may default to a cycle length; leave unresolved until founder approval.
   */
  OWNER_SETTLEMENT_CYCLE: '[[OWNER_SETTLEMENT_CYCLE]]',
} as const;

export type LegalContentPlaceholderKey = keyof typeof LEGAL_CONTENT_PLACEHOLDERS;

export type LegalContentPlaceholderValues = Partial<
  Record<LegalContentPlaceholderKey, string>
>;
