/**
 * Re-export marketplace financial SSOT for legal-content interpolation.
 * Legal text must import numbers from here (or marketplace-financial-policy)
 * so commercial figures cannot drift from the booking engine.
 */
export {
  STANDARD_COMMISSION_PERCENT,
  VERIFIED_COMMISSION_PERCENT,
  DEPOSIT_PERCENT,
  FULL_PAYMENT_WITHIN_HOURS,
  BALANCE_DUE_HOURS_BEFORE_START,
  CANCELLATION_FREE_UNTIL_HOURS,
  CANCELLATION_CHARGE_30_UNTIL_HOURS,
  CANCELLATION_CHARGE_50_UNTIL_HOURS,
  CANCELLATION_CHARGE_PERCENT_FREE,
  CANCELLATION_CHARGE_PERCENT_TIER_30,
  CANCELLATION_CHARGE_PERCENT_TIER_50,
  CANCELLATION_CHARGE_PERCENT_TIER_100,
  OWNER_CANCEL_PENALTY_FREE_UNTIL_HOURS,
  OWNER_CANCEL_PENALTY_TIER_10_UNTIL_HOURS,
  OWNER_CANCEL_PENALTY_PERCENT_FREE,
  OWNER_CANCEL_PENALTY_PERCENT_TIER_10,
  OWNER_CANCEL_PENALTY_PERCENT_TIER_20,
  OWNER_PENALTY_MIN_JOD,
  OWNER_PENALTY_MAX_JOD,
  CUSTOMER_NO_SHOW_GRACE_MINUTES,
  MAX_CUSTOMER_RESCHEDULES,
  CHECK_IN_OPEN_HOURS_BEFORE_START,
  CHECK_IN_EXPIRE_MINUTES_AFTER_START,
  RESCHEDULE_COUNTERPARTY_EXPIRE_HOURS,
} from '../marketplace-financial-policy';
