import type { PublicPropertyDetail, PublicPropertySummary } from './types';

/** Demo data for Phase 1 UI — no owner contact or exact address exposed */
export const MOCK_PROPERTIES: PublicPropertyDetail[] = [
  {
    id: '1',
    slug: 'chalet-emerald-dead-sea',
    type: 'chalet',
    titleAr: 'شاليه إميرالد — إطلالة البحر الميت',
    titleEn: 'Emerald Chalet — Dead Sea View',
    descriptionAr:
      'شاليه خاص بمسبح مدفأ وحديقة واسعة، مثالي للعائلات الباحثة عن الخصوصية والهدوء قرب البحر الميت.',
    descriptionEn:
      'Private chalet with heated pool and spacious garden, ideal for families seeking privacy near the Dead Sea.',
    city: 'dead_sea',
    area: 'سويمة',
    approximateLocation: 'منطقة البحر الميت — سويمة',
    capacity: 18,
    bedrooms: 4,
    bathrooms: 3,
    poolsCount: 1,
    rating: 4.9,
    reviewCount: 47,
    basePrice: 480,
    currency: 'JOD',
    verificationStatus: 'platform_verified',
    hasPlatformDeal: true,
    allowsFamilies: true,
    allowsYouth: false,
    hasPool: true,
    hasIndoorPool: false,
    hasHeatedPool: true,
    hasFootballField: false,
    allowsOvernight: true,
    allowsEvents: false,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    imageUrl: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&q=80',
        altAr: 'شاليه بإطلالة ومسبح',
        altEn: 'Chalet with pool view',
      },
      {
        url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80',
        altAr: 'منطقة المسبح',
        altEn: 'Pool area',
      },
    ],
    amenityKeys: ['pool', 'bbq', 'ac', 'wifi', 'parking'],
    rulesAr: ['ممنوع التدخين داخل الشاليه', 'الحد الأقصى للضيوف حسب الحجز', 'احترام أوقات الدخول والخروج'],
    rulesEn: ['No smoking inside', 'Guest limit per booking', 'Respect check-in/out times'],
  },
  {
    id: '2',
    slug: 'villa-naour-pool',
    type: 'villa',
    titleAr: 'فيلا ناعور — مسبح وملعب',
    titleEn: 'Naour Villa — Pool & Football',
    descriptionAr: 'فيلا واسعة للشباب والعائلات مع مسبح خارجي وملعب كرة ومنطقة شواء.',
    descriptionEn: 'Spacious villa for youth and families with outdoor pool, football field, and BBQ area.',
    city: 'amman',
    area: 'ناعور',
    approximateLocation: 'ناعور — ضواحي عمان',
    capacity: 30,
    bedrooms: 5,
    bathrooms: 4,
    poolsCount: 1,
    rating: 4.7,
    reviewCount: 32,
    basePrice: 620,
    currency: 'JOD',
    verificationStatus: 'platform_reviewed',
    hasPlatformDeal: false,
    allowsFamilies: true,
    allowsYouth: true,
    hasPool: true,
    hasIndoorPool: false,
    hasHeatedPool: false,
    hasFootballField: true,
    allowsOvernight: true,
    allowsEvents: false,
    checkInTime: '13:00',
    checkOutTime: '11:00',
    imageUrl: 'https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=800&q=80',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?w=1200&q=80',
        altAr: 'فيلا بمسبح خاص',
        altEn: 'Villa with private pool',
      },
    ],
    amenityKeys: ['pool', 'football', 'bbq', 'wifi', 'parking'],
    rulesAr: ['ممنوع الحفلات الصاخبة بعد منتصف الليل', 'الالتزام بعدد الضيوف'],
    rulesEn: ['No loud parties after midnight', 'Stick to guest count'],
  },
  {
    id: '3',
    slug: 'istiraha-jerash-garden',
    type: 'istiraha',
    titleAr: 'استراحة جرش — حديقة ومسبح',
    titleEn: 'Jerash Istiraha — Garden & Pool',
    descriptionAr: 'استراحة هادئة محاطة بأشجار الزيتون، مناسبة للعائلات والمناسبات الصغيرة.',
    descriptionEn: 'Quiet istiraha surrounded by olive trees, suitable for families and small gatherings.',
    city: 'jerash',
    area: 'جرش',
    approximateLocation: 'محيط جرش',
    capacity: 25,
    bedrooms: 3,
    bathrooms: 2,
    poolsCount: 1,
    rating: 4.8,
    reviewCount: 21,
    basePrice: 175,
    currency: 'JOD',
    verificationStatus: 'owner_uploaded',
    hasPlatformDeal: true,
    allowsFamilies: true,
    allowsYouth: true,
    hasPool: true,
    hasIndoorPool: false,
    hasHeatedPool: false,
    hasFootballField: false,
    allowsOvernight: false,
    allowsEvents: true,
    checkInTime: '10:00',
    checkOutTime: '22:00',
    imageUrl: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=800&q=80',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?w=1200&q=80',
        altAr: 'استراحة بين الطبيعة',
        altEn: 'Countryside istiraha',
      },
    ],
    amenityKeys: ['pool', 'bbq', 'garden', 'parking'],
    rulesAr: ['يومية فقط — بدون مبيت', 'الحفاظ على نظافة المسبح'],
    rulesEn: ['Day use only — no overnight', 'Keep pool area clean'],
  },
  {
    id: '4',
    slug: 'farm-salt-events',
    type: 'farm',
    titleAr: 'مزرعة السلط — مناسبات وعائلات',
    titleEn: 'Salt Farm — Events & Families',
    descriptionAr: 'مساحة ترفيهية خاصة للعائلات والمناسبات مع قاعة خارجية ومسبح للأطفال.',
    descriptionEn: 'Private recreational space for families and events with outdoor hall and kids pool.',
    city: 'salt',
    area: 'السلط',
    approximateLocation: 'ضواحي السلط',
    capacity: 40,
    bedrooms: 2,
    bathrooms: 3,
    poolsCount: 2,
    rating: 4.6,
    reviewCount: 15,
    basePrice: 340,
    currency: 'JOD',
    verificationStatus: 'unverified',
    hasPlatformDeal: false,
    allowsFamilies: true,
    allowsYouth: true,
    hasPool: true,
    hasIndoorPool: true,
    hasHeatedPool: false,
    hasFootballField: true,
    allowsOvernight: true,
    allowsEvents: false,
    checkInTime: '12:00',
    checkOutTime: '12:00',
    imageUrl: 'https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=800&q=80',
    images: [
      {
        url: 'https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=1200&q=80',
        altAr: 'مزرعة ترفيهية خضراء',
        altEn: 'Green leisure farm',
      },
    ],
    amenityKeys: ['pool', 'kids_pool', 'bbq', 'events', 'parking', 'wifi'],
    rulesAr: ['تأمين عربون عبر المنصة عند الحجز', 'عدم إدخال ضيوف إضافيين'],
    rulesEn: ['Deposit via platform when booking', 'No extra guests'],
  },
];

export function getMockPropertySummaries(): PublicPropertySummary[] {
  return MOCK_PROPERTIES.map(
    ({ rulesAr: _ra, rulesEn: _re, images: _im, descriptionAr: _da, descriptionEn: _de, ...summary }) =>
      summary,
  );
}

export function getMockPropertyBySlug(slug: string): PublicPropertyDetail | undefined {
  return MOCK_PROPERTIES.find((p) => p.slug === slug);
}
