-- Align remaining 10C.1 columns with Prisma (additive)

ALTER TABLE "PartnerCommercialTerms" ADD COLUMN IF NOT EXISTS "version" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "PartnerCommercialTerms" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "PartnerAgreement" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "PartnerAgreement" ADD COLUMN IF NOT EXISTS "legalReviewPlaceholder" BOOLEAN NOT NULL DEFAULT true;
